apiVersion: v1
kind: Service
metadata:
  name: prowlarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prowlarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr-exporter
      app.kubernetes.io/instance: prowlarr-exporter
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prowlarr-exporter-lab-member87-xyz
  namespace: monitoring
spec:
  secretName: prowlarr-exporter-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - prowlarr.metrics.lab.member87.xyz
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prowlarr-exporter-ingressroute
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prowlarr.metrics.lab.member87.xyz`)
      kind: Rule
      services:
        - name: prowlarr-exporter
          port: 9707
  tls:
    secretName: prowlarr-exporter-certificate-secret
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: prowlarr-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prowlarr-exporter
    app.kubernetes.io/instance: prowlarr-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: prowlarr-exporter
      app.kubernetes.io/instance: prowlarr-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prowlarr-exporter
        app.kubernetes.io/instance: prowlarr-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: prowlarr-exporter
          image: ghcr.io/onedr0p/exportarr:v1.5.3
          imagePullPolicy: IfNotPresent
          args:
            - prowlarr
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://192.168.1.123:9696/"
            - name: APIKEY
              valueFrom:
                secretKeyRef:
                  name: prowlarr-exporter
                  key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
