apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: qbittorrent-exporter
    app.kubernetes.io/instance: qbittorrent-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: qbittorrent-exporter
    app.kubernetes.io/instance: qbittorrent-exporter
  ports:
    - name: monitoring
      port: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: qbittorrent-exporter
    app.kubernetes.io/instance: qbittorrent-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-exporter
      app.kubernetes.io/instance: qbittorrent-exporter
  endpoints:
    - port: monitoring
      interval: 4m
      scrapeTimeout: 90s
      path: /metrics
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: qbittorrent-exporter-lab-member87-xyz
  namespace: monitoring
spec:
  secretName: qbittorrent-exporter-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - qbittorrent.metrics.lab.member87.xyz
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: qbittorrent-exporter-ingressroute
  namespace: monitoring
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`qbittorrent.metrics.lab.member87.xyz`)
      kind: Rule
      services:
        - name: qbittorrent-exporter
          port: 8000
  tls:
    secretName: qbittorrent-exporter-certificate-secret
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: qbittorrent-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: qbittorrent-exporter
    app.kubernetes.io/instance: qbittorrent-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: qbittorrent-exporter
      app.kubernetes.io/instance: qbittorrent-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: qbittorrent-exporter
        app.kubernetes.io/instance: qbittorrent-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: qbittorrent-exporter
          image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: QBITTORRENT_HOST
              value: "192.168.1.123"
            - name: QBITTORRENT_PORT
              value: "8080"
            - name: EXPORTER_PORT
              value: "8000"
            - name: QBITTORRENT_USER
              value: root
            - name: QBITTORRENT_PASS
              valueFrom:
                secretKeyRef:
                  name: qbittorrent-exporter
                  key: password
          ports:
            - name: monitoring
              containerPort: 8000
          livenessProbe:
            httpGet:
              path: /metrics
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
