apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# - deployment.yaml
- longhorn-critical-priorityclass.yaml

helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io/
    version: v1.8.1 
    releaseName: longhorn 
    namespace: longhorn
    valuesInline:
      preUpgradeChecker:
        jobEnabled: false
      ingress:
        enabled: false
      service:
        ui:
          type: NodePort
          nodePort: 31000 

