apiVersion: v1
kind: Service
metadata:
  name: pihole-service
spec:
  selector:
    app: pihole
  ports:
  - name: dns-tcp
    protocol: TCP
    port: 53
    targetPort: 53
    nodePort: 32701
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
    nodePort: 32701 
  - name: http-web
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32700
  type: NodePort
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800 
