apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomize-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/member87/nixos
        revision: home-server
        directories:
          - path: kustomize/*
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/member87/nixos
        targetRevision: home-server
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
