# kustomize/ApplicationSet.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kustomized-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: "https://github.com/member87/nixos"
        revision: "home-server" 
        directories:
          - path: kustomize/*
  template:
    metadata:
      name: '{{path.basename}}-app'
      namespace: argocd
    spec:
      project: default

      source:
        repoURL: 'https://github.com/member87/nixos'
        targetRevision: 'home-server' 
        path: 'kustomize/'
        kustomize: {}

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
