apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pihole 
  template:
    metadata:
      labels:
        app: pihole 
    spec:
      containers:
      - name: pihole 
        image: pihole/pihole
        ports:
        - containerPort: 80
        volumeMounts:
        - name: pihole-data
          mountPath: /etc/pihole/
        env:
        - name: JELLYFIN_KEY
          value: "06d9613bae3d4eeeaa6005eb1cbd6784"
        - name: JELLYFIN_URL
          value: "http://192.168.1.123:8096"
        - name: TZ
          value: 'Europe/London'
        - name: FTLCONF_webserver_api_password
          value: 'password'
