apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pihole 

resources:
- deployment.yaml
- service.yaml
- namespace.yaml


securityContext:
  capabilities:
    add:
      - NET_ADMIN
      - NET_RAW

# configMapGenerator:
# - name: pihole-config
#   files:
