apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        env:
        - name: TZ
          value: 'Europe/London'
        - name: FTLCONF_dns_specialDomains_iCloudPrivateRelay
          value: "false"
        - name: FTLCONF_webserver_api_password
          value: 'password'
        - name: FTLCONF_dns_domain
          value: 'lab.member87.xyz'
        - name: FTLCONF_misc_etc_dnsmasq_d
          value: "true"
        - name: FTLCONF_misc_dnsmasq_lines
          value: "address=/lab.member87.xyz/192.168.1.250"
        - name: INTERFACE
          value: 'all'
        - name: REV_SERVER
          value: "true"
        - name: REV_SERVER_DOMAIN
          value: "lab.member87.xyz"
        - name: REV_SERVER_TARGET
          value: "192.168.1.1"
        - name: REV_SERVER_CIDR
          value: "192.168.1.0/24"
        volumeMounts:
        - name: pihole-persistent-storage
          mountPath: /etc/pihole         
      volumes:
      - name: pihole-persistent-storage
        persistentVolumeClaim:
          claimName: pihole-config-logs-pvcrwx

---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-config-logs-pvcrwx
  namespace: pihole            
  annotations:
    longhorn.io/number-of-replicas: "1" 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-lab-member87-xyz
  namespace: pihole
spec:
  secretName: pihole-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - pihole.lab.member87.xyz
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pihole-ingressroute
  namespace: pihole
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pihole.lab.member87.xyz`)
      kind: Rule
      services:
        - name: pihole-service
          port: 80
  tls:
    secretName: pihole-certificate-secret
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-service 
  namespace: pihole
spec:
  selector:
    app: pihole   
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  namespace: pihole 
  labels:
    app: pihole
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerIP: 192.168.1.249
  selector:
    app: pihole
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.1.200-192.168.1.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: pihole-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - pihole-pool
