apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glance.labels" . | nindent 4 }}
data:
  glance.yml: |-
{{ .Files.Get "files/glance.yaml" | indent 4 }}
