apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: glance
  template:
    metadata:
      labels:
        app: glance
    spec:
      
      volumes:
      - name: config-volume
        configMap:
          name: glance-config 
      containers:
      - name: glance
        image: glanceapp/glance
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume 
          mountPath: /app/config
          readOnly: true
        env:
        - name: JELLYFIN_KEY
          value: "06d9613bae3d4eeeaa6005eb1cbd6784"
        - name: JELLYFIN_URL
          value: "http://192.168.1.123:8096"


