{
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    opencode
    ghostty
    alejandra
    agenix
    bat
    brave
    cargo
    curl
    ffmpeg
    hyprshot
    hyprpaper
    jellyfin-media-player
    jq
    gcc
    go
    gnumake
    gphoto2
    killall
    lua-language-server
    ledger-live-desktop
    libnotify
    librewolf
    lutris
    lxqt.lxqt-openssh-askpass
    lxqt.lxqt-policykit
    mangohud
    neovim
    nodejs
    nil
    nixfmt-rfc-style
    obsidian
    pavucontrol
    playerctl
    python3
    protontricks
    obs-studio
    rose-pine-hyprcursor
    r2modman
    ripgrep
    socat
    treefmt
    unzip
    legcord
    wineWowPackages.stable
    wl-clipboard
    wget
    freerdp3
    inputs.zen-browser.packages."${pkgs.system}".default
  ];
}
