apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: glance-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/member87/nixos.git
    targetRevision: home-server
    path: argocd/glance/
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
