apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: simple-nginx
  namespace: argocd 
spec:
  project: default 

  source:
    repoURL: https://github.com/YOUR_GIT_REPO/YOUR_REPO_NAME.git 
    targetRevision: HEAD 
    path: kubernetes/nginx 

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
    syncOptions:
      - CreateNamespace=true
