apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/member87/argocd-secrets.git 
    targetRevision: home-server
    path: /
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 
