apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 35.2.0
      helm:
        values: |
          additionalArguments:
            - "--serversTransport.insecureSkipVerify=true"

          providers:
            kubernetesCRD:
              enabled: true
              ingressClass: traefik-external
            kubernetesIngress:
              enabled: true
              publishedService:
                enabled: false

          deployment:
            enabled: true
            replicas: 3

          dashboard:
            enabled: true

          entryPoints:
            web:
              address: ":80"
            websecure:
              address: ":443"
            metrics:
              address: ":9100"

          ingressRoute:
            dashboard:
              enabled: false

          rbac:
            enabled: true

          service:
            enabled: true
            type: LoadBalancer
            spec: 
              loadBalancerIP: 192.168.1.250

          ports:
            web:
              redirectTo: websecure
            websecure:
              tls:
                enabled: true

          metrics:
            prometheus:
              entryPoint: metrics 
              enabled: true

          service:
            type: LoadBalancer
            spec:
              externalTrafficPolicy: Local 


  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.lab.member87.xyz`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
