apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  project: default
  sources:
    - chart: traefik
      repoURL: https://traefik.github.io/charts
      targetRevision: 35.2.0
      helm:
        values: |
          additionalArguments:
            - "--serversTransport.insecureSkipVerify=true"
            - "--log.level=DEBUG"
            - "--tls.options.default.cipherSuites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256,TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256"

          providers:
            kubernetesCRD:
              enabled: true
              ingressClass: traefik-external
            kubernetesIngress:
              enabled: true
              publishedService:
                enabled: false

          deployment:
            enabled: true
            replicas: 1

          dashboard:
            enabled: true

          entryPoints:
            web:
              address: ":80"
              http:
                redirections:
                  entryPoint:
                    to: websecure
                    scheme: https
            websecure:
              address: ":443"
              http:
                tls:
                  enabled: true
            metrics:
              address: ":9100"

          ingressRoute:
            dashboard:
              enabled: false

          rbac:
            enabled: true

          service:
            enabled: true
            type: LoadBalancer
            spec:
              loadBalancerIP: 192.168.1.250 
              externalTrafficPolicy: Local 
          
          ports:
            web:
              port: 80
              exposedPort: 80
            websecure:
              port: 443
              exposedPort: 443

          metrics:
            prometheus:
              entryPoint: metrics
              enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`traefik.lab.member87.xyz`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
