apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 27.13.0
      helm:
        valueFiles:
          - values.yaml
  automated:
      prune: true
      selfHeal: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

