apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  project: default
  sources:
    - chart: prometheus
      repoURL: https://prometheus-community.github.io/helm-charts
      targetRevision: 27.12.1
      helm:
        valueFiles:
          - prometheus-values.yaml 
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus 
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: prometheus
spec:
  selector:
    app: prometheus-server 
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090 
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-cert 
  namespace: prometheus
spec:
  secretName: prometheus-certificate-secret
  issuerRef:
    name: cloudflare-cluster-issuer
    kind: ClusterIssuer
  dnsNames:
    - prometheus.lab.member87.xyz
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus-ingressroute 
  namespace: prometheus 
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`prometheus.lab.member87.xyz`)
      kind: Rule
      services:
        - name: prometheus-service
          port: 80 
  tls:
    secretName: prometheus-certificate-secret

