

server:
  ingress:
    enabled: true
    className: traefik 
    hosts:
      - host: prometheus.lab.member87.xyz
        paths:
          - path: /
            pathType: Prefix
    tls:
      - hosts:
          - prometheus.lab.member87.xyz
        secretName: prometheus-dashboard-tls-secret 

  serviceAccount:
    create: true
    name: prometheus-server
