grafana:
  enabled: true
  ingress:
    enabled: false 
  
  adminUser: admin
  adminPassword: admin
  
  grafana.ini:
    auth:
      disable_login_form: false
    auth.anonymous:
      enabled: false

prometheus:
  ingress:
    enabled: false 

alertmanager:
  ingress:
    enabled: false 
