grafana:
  enabled: true
  ingress:
    enabled: false 
  
  adminUser: admin
  adminPassword: prom-operator


  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: false

  additionalDataSources:
    - name: 'Prometheus'
      type: 'prometheus'
      url: 'https://prometheus.lab.member87.xyz'
      access: 'proxy'
      isDefault: true
      uid: 'prometheus-stack-default'
      jsonData:
        timeInterval: "30s"

  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: false

 
prometheus:
  ingress:
    enabled: false 
  prometheusSpec:
    externalUrl: "https://prometheus.lab.member87.xyz"

alertmanager:
  ingress:
    enabled: false 
