grafana:
  enabled: true
  ingress:
    enabled: false 
  
  adminUser: admin
  adminPassword: prom-operator

  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: false

 
prometheus:
  ingress:
    enabled: false 
  prometheusSpec:
    externalUrl: "https://prometheus.lab.member87.xyz"

alertmanager:
  ingress:
    enabled: false 
