grafana:
  enabled: true
  ingress:
    enabled: false 
  
  adminUser: admin
  adminPassword: prom-operator
  
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Prometheus
          type: prometheus
          url: https://prometheus.lab.member87.xyz
          access: proxy
          isDefault: true
          jsonData:
            httpMethod: POST
            timeInterval: 30s
        - name: Alertmanager
          type: alertmanager
          url: https://alertmanager.lab.member87.xyz
          access: proxy
          jsonData:
            handleGrafanaManagedAlerts: false
            implementation: prometheus

prometheus:
  ingress:
    enabled: false 

alertmanager:
  ingress:
    enabled: false 
