grafana:
  enabled: true
  ingress:
    enabled: false 
  
  adminUser: admin
  adminPassword: prom-operator
  
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: false
      
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: https://prometheus.lab.member87.xyz
      isDefault: true

prometheus:
  ingress:
    enabled: false 

alertmanager:
  ingress:
    enabled: false 
