grafana:
  enabled: true
  ingress:
    enabled: false 
  
  adminUser: admin
  adminPassword: prom-operator

  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
      url: "https://prometheus.lab.member87.xyz"

  
  grafana.ini:
    auth:
      disable_login_form: true
    auth.anonymous:
      enabled: false

 
prometheus:
  ingress:
    enabled: false 

alertmanager:
  ingress:
    enabled: false 
