apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-deployment
  namespace: pihole
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole
        ports:
        - containerPort: 80
          protocol: TCP
        - containerPort: 53
          protocol: TCP
        - containerPort: 53
          protocol: UDP
        env:
        - name: TZ
          value: 'Europe/London'
        - name: FTLCONF_webserver_api_password
          value: 'password'
---
apiVersion: v1
kind: Namespace
metadata:
  name: pihole
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-web
  labels: 
    app.kubernetes.io/name: pi-hole
    pi.hole/role: read-write
spec:
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
  selector:
    app.kubernetes.io/name: pihole
    pi.hole/role: read-write
  ports:
  - port: 80
    targetPort: http
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-dns
  labels:
    app.kubernetes.io/name: pi-hole
  annotations:
    io.cilium/lb-ipam-sharing-key: "pihole-svc"
    io.cilium/lb-ipam-ips: "10.2.0.6"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  - port: 53
    targetPort: 53
    protocol: UDP
    name: dns-udp
  selector:
    app.kubernetes.io/name: pihole
